apiVersion: v1
data:
  nginx.conf: |
    server {
        listen 80;
        server_name  netology.ru www.netology.ru;
        access_log  /var/log/nginx/domains/netology.ru-access.log  main;
        error_log   /var/log/nginx/domains/netology.ru-error.log info;
        location / {
            include proxy_params;
            proxy_pass http://10.10.10.10:8080/;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-30T09:11:54Z"
  name: nginx-config
  namespace: default
  resourceVersion: "22921"
  uid: 5b86d935-ff9d-4d92-99d2-e8c74f2a7b3e
